In [133]:
import pandas as pd
import numpy as np
import seaborn as sns
from mafese import Data
import matplotlib.pyplot as plt 

#for checking the performance of model
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv('new_kidney_disease.csv')

cols = df.columns
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
data=Data(X,y)

data.split_train_test(test_size=0.2, inplace=True)

 For Unsupervised Selector

In [134]:
from mafese.unsupervised import UnsupervisedSelector
feat_selector = UnsupervisedSelector(problem='classification', method='DR', n_features=5)
feat_selector.fit(data.X_train)
print(feat_selector.selected_feature_masks)
print(feat_selector.selected_feature_solution)
print(feat_selector.selected_feature_indexes)

[False False False False False  True  True False False False False False
 False False False False False False  True  True False  True False False]
[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0]
[ 5  6 18 19 21]


In [135]:
selected_feature_indices = feat_selector.selected_feature_indexes

X_train_selected = data.X_train.iloc[:, selected_feature_indices]
X_test_selected = data.X_test.iloc[:, selected_feature_indices]

model = XGBClassifier()
model.fit(X_train_selected, data.y_train)


y_pred = model.predict(X_test_selected)
accuracy = accuracy_score(data.y_test, y_pred)

print("Selected Features Accuracy:", accuracy)

Selected Features Accuracy: 0.9375


###### Accuracy For Unsupervised Selector is 93 %

In [136]:
#For Filter Selector

In [137]:
from mafese.filter import FilterSelector

feat_selector = FilterSelector(problem='classification', method='SPEARMAN', n_features=5)
X_train_np = np.array(data.X_train)
y_train_np = np.array(data.y_train)
feat_selector.fit(X_train_np, y_train_np)

print(feat_selector.selected_feature_masks)
print(feat_selector.selected_feature_solution)
print(feat_selector.selected_feature_indexes)


[False False False  True False False False False False False  True  True
 False False False False False False  True  True False False False False]
[0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0]
[ 3 10 11 18 19]


In [138]:
selected_feature_indices = feat_selector.selected_feature_indexes

X_train_selected = data.X_train.iloc[:, selected_feature_indices]
X_test_selected = data.X_test.iloc[:, selected_feature_indices]

model = XGBClassifier()
model.fit(X_train_selected, data.y_train)


y_pred = model.predict(X_test_selected)
accuracy = accuracy_score(data.y_test, y_pred)

print("Selected Features Accuracy:", accuracy)

Selected Features Accuracy: 0.9


###### Accuracy For Filter Selector is 90 %

In [139]:
#For Lasso Selector

In [140]:
from mafese.embedded.lasso import LassoSelector
feat_selector = LassoSelector(problem="classification", estimator="lasso", estimator_paras={"alpha": 0.1})
feat_selector.fit(data.X_train,data.y_train)
print(feat_selector.selected_feature_masks)
print(feat_selector.selected_feature_solution)
print(feat_selector.selected_feature_indexes)

[ True  True False  True False False False False False  True  True False
  True False  True  True  True False False False False False False False]
[1 1 0 1 0 0 0 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 0]
[ 0  1  3  9 10 12 14 15 16]


In [141]:
selected_feature_indices = feat_selector.selected_feature_indexes

X_train_selected = data.X_train.iloc[:, selected_feature_indices]
X_test_selected = data.X_test.iloc[:, selected_feature_indices]

model = XGBClassifier()
model.fit(X_train_selected, data.y_train)


y_pred = model.predict(X_test_selected)
accuracy = accuracy_score(data.y_test, y_pred)

print("Selected Features Accuracy:", accuracy)

Selected Features Accuracy: 0.975


###### Accuracy for Lasso Selector is 97%

In [142]:
#For Tree Selector

In [143]:
from mafese.embedded.tree import TreeSelector
feat_selector = TreeSelector(problem="classification", estimator="tree")
feat_selector.fit(data.X_train,data.y_train)
print(feat_selector.selected_feature_masks)
print(feat_selector.selected_feature_solution)
print(feat_selector.selected_feature_indexes)

[False False  True  True False  True False False False False False False
 False False  True  True False False  True  True False  True False False]
[0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 0 0]
[ 2  3  5 14 15 18 19 21]


In [144]:
selected_feature_indices = feat_selector.selected_feature_indexes

X_train_selected = data.X_train.iloc[:, selected_feature_indices]
X_test_selected = data.X_test.iloc[:, selected_feature_indices]

model = XGBClassifier()
model.fit(X_train_selected, data.y_train)


y_pred = model.predict(X_test_selected)
accuracy = accuracy_score(data.y_test, y_pred)

print("Selected Features Accuracy:", accuracy)

Selected Features Accuracy: 0.975


###### Accuracy for Tree Selector is 97%

In [145]:
#For Sequential Selector

In [146]:
from mafese.wrapper.sequential import SequentialSelector
feat_selector = SequentialSelector(problem="classification", estimator="knn", n_features=3, direction="forward")
feat_selector.fit(data.X_train,data.y_train)
print(feat_selector.selected_feature_masks)
print(feat_selector.selected_feature_solution)
print(feat_selector.selected_feature_indexes)

[False False False  True False  True False False False False False  True
 False False False False False False False False False False False False]
[0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[ 3  5 11]


In [147]:
selected_feature_indices = feat_selector.selected_feature_indexes

X_train_selected = data.X_train.iloc[:, selected_feature_indices]
X_test_selected = data.X_test.iloc[:, selected_feature_indices]

model = XGBClassifier()
model.fit(X_train_selected, data.y_train)


y_pred = model.predict(X_test_selected)
accuracy = accuracy_score(data.y_test, y_pred)

print("Selected Features Accuracy:", accuracy)

Selected Features Accuracy: 0.95


###### Accuracy Using Sequential Selector is 95%

In [148]:
#Using MhaSelector

In [149]:
from mafese.wrapper.mha import MhaSelector
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from mafese import Data
import pandas as pd
import numpy as np

df = pd.read_csv('new_kidney_disease.csv')
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
data = Data(X,y)
data.split_train_test(test_size=0.2)
print(data.X_train.shape, data.X_test.shape)  
X_train = np.array(data.X_train)
X_test = np.array(data.X_test)
y_train = np.array(data.y_train)
y_test = np.array(data.y_test)

feat_selector = MhaSelector(problem="classification", estimator="knn",
                            optimizer="BaseGA", optimizer_paras=None,
                            transfer_func="vstf_01", obj_name="AS")

feat_selector.fit(X_train, y_train, fit_weights=(0.9, 0.1), verbose=True)

print(feat_selector.selected_feature_masks)
print(feat_selector.selected_feature_solution)

print(feat_selector.selected_feature_indexes)

2024/11/06 08:16:48 AM, INFO, mealpy.evolutionary_based.GA.BaseGA: Solving 2-objective optimization problem with weights: [1. 0.].


(320, 24) (80, 24)


2024/11/06 08:16:52 AM, INFO, mealpy.evolutionary_based.GA.BaseGA: >Problem: P, Epoch: 1, Current best: 0.7320833333333333, Global best: 0.7320833333333333, Runtime: 1.69001 seconds
2024/11/06 08:16:52 AM, INFO, mealpy.evolutionary_based.GA.BaseGA: >Problem: P, Epoch: 2, Current best: 0.8483333333333333, Global best: 0.8483333333333333, Runtime: 0.65962 seconds
2024/11/06 08:16:53 AM, INFO, mealpy.evolutionary_based.GA.BaseGA: >Problem: P, Epoch: 3, Current best: 0.7795833333333334, Global best: 0.8483333333333333, Runtime: 0.37467 seconds
2024/11/06 08:16:53 AM, INFO, mealpy.evolutionary_based.GA.BaseGA: >Problem: P, Epoch: 4, Current best: 0.8370833333333334, Global best: 0.8483333333333333, Runtime: 0.37327 seconds
2024/11/06 08:16:54 AM, INFO, mealpy.evolutionary_based.GA.BaseGA: >Problem: P, Epoch: 5, Current best: 0.8341666666666666, Global best: 0.8483333333333333, Runtime: 0.37389 seconds
2024/11/06 08:16:54 AM, INFO, mealpy.evolutionary_based.GA.BaseGA: >Problem: P, Epoch: 6, 

[False False False  True False  True False False  True False False False
 False False False False False False False False False False False False]
[0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[3 5 8]


In [150]:
selected_feature_indices = feat_selector.selected_feature_indexes

X_train_selected = data.X_train.iloc[:, selected_feature_indices]
X_test_selected = data.X_test.iloc[:, selected_feature_indices]

model = XGBClassifier()
model.fit(X_train_selected, data.y_train)


y_pred = model.predict(X_test_selected)
accuracy = accuracy_score(data.y_test, y_pred)

print("Selected Features Accuracy:", accuracy)

Selected Features Accuracy: 0.95


###### Accuracy For MhaSelector is 95%

In [151]:
import pandas as pd
import numpy as np
from mafese.wrapper.mha import MultiMhaSelector
from mafese import Data
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, f1_score

# Load dataset
df = pd.read_csv('new_kidney_disease.csv')
X = df.iloc[:, :-1].to_numpy()  
y = df.iloc[:, -1].to_numpy()
feature_names = df.columns[:-1]  

# Initialize and split data
data = Data(X, y)
data.split_train_test(test_size=0.2)
X_train, y_train, X_test, y_test = data.X_train, data.y_train, data.X_test, data.y_test

# Initialize feature selector
list_optimizers = ("OriginalWOA", "OriginalGWO", "OriginalTLO", "OriginalGSKA")
list_paras = [{"epoch": 10, "pop_size": 30}] * len(list_optimizers)
feat_selector = MultiMhaSelector(
    problem="classification",
    estimator="xgb",
    list_optimizers=list_optimizers,
    list_optimizer_paras=list_paras,
    transfer_func="vstf_01",
    obj_name="AS"
)

# Fit feature selector
feat_selector.fit(X_train, y_train)

# Gather selected indices and feature names
selected_features = {}
trials = ["trial1", "trial2", "trial3"]

for trial in trials:
    for optimizer in list_optimizers:
        indices = feat_selector.list_selected_feature_indexes.get(trial, {}).get(optimizer, [])
        selected_feature_names = feature_names[indices] if len(indices) > 0 else []
        selected_features[(trial, optimizer)] = (indices, selected_feature_names)
        print(f"Selected indices for {trial} with {optimizer}: {indices}")
        print(f"Feature names for {trial} with {optimizer}: {list(selected_feature_names)}")

# Initialize dictionary for results
results = {}

# Calculate cross-validation and test metrics
for (trial, optimizer), (indices, _) in selected_features.items():
    if len(indices) > 0:  
        X_selected_train, X_selected_test = X_train[:, indices], X_test[:, indices]
        
        # Cross-validate the model
        model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
        cv_accuracy = cross_val_score(model, X_selected_train, y_train, cv=5, scoring='accuracy').mean()
        
        # Fit and evaluate on test set
        model.fit(X_selected_train, y_train)
        y_pred = model.predict(X_selected_test)
        test_accuracy = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average='weighted')
        
        # Store results
        results[(trial, optimizer)] = {
            'cv_accuracy': cv_accuracy,
            'test_accuracy': test_accuracy,
            'f1_score': f1
        }

# Print summarized results
for (trial, optimizer), metrics in results.items():
    print(f"Performance for {trial} with {optimizer} - "
          f"CV Accuracy: {metrics['cv_accuracy']:.4f}, "
          f"Test Accuracy: {metrics['test_accuracy']:.4f}, "
          f"F1 Score: {metrics['f1_score']:.4f}")


2024/11/06 08:17:27 AM, INFO, mealpy.swarm_based.WOA.OriginalWOA: Solving 2-objective optimization problem with weights: [1. 0.].
2024/11/06 08:17:44 AM, INFO, mealpy.swarm_based.WOA.OriginalWOA: >Problem: P, Epoch: 1, Current best: 0.8316666666666666, Global best: 0.8316666666666666, Runtime: 8.54954 seconds
2024/11/06 08:17:51 AM, INFO, mealpy.swarm_based.WOA.OriginalWOA: >Problem: P, Epoch: 2, Current best: 0.8512500000000001, Global best: 0.8512500000000001, Runtime: 7.46719 seconds
2024/11/06 08:18:00 AM, INFO, mealpy.swarm_based.WOA.OriginalWOA: >Problem: P, Epoch: 3, Current best: 0.8625, Global best: 0.8625, Runtime: 8.92968 seconds
2024/11/06 08:18:06 AM, INFO, mealpy.swarm_based.WOA.OriginalWOA: >Problem: P, Epoch: 4, Current best: 0.8666666666666667, Global best: 0.8666666666666667, Runtime: 5.75072 seconds
2024/11/06 08:18:13 AM, INFO, mealpy.swarm_based.WOA.OriginalWOA: >Problem: P, Epoch: 5, Current best: 0.8666666666666667, Global best: 0.8666666666666667, Runtime: 6.720

Solving problem: P using algorithm: OriginalWOA, on the: 1 trial, with best fitness: 0.8791666666666667


2024/11/06 08:18:54 AM, INFO, mealpy.swarm_based.WOA.OriginalWOA: >Problem: P, Epoch: 1, Current best: 0.8608333333333332, Global best: 0.8608333333333332, Runtime: 8.77664 seconds
2024/11/06 08:19:01 AM, INFO, mealpy.swarm_based.WOA.OriginalWOA: >Problem: P, Epoch: 2, Current best: 0.8608333333333332, Global best: 0.8608333333333332, Runtime: 7.16892 seconds
2024/11/06 08:19:11 AM, INFO, mealpy.swarm_based.WOA.OriginalWOA: >Problem: P, Epoch: 3, Current best: 0.8679166666666667, Global best: 0.8679166666666667, Runtime: 9.08917 seconds
2024/11/06 08:19:17 AM, INFO, mealpy.swarm_based.WOA.OriginalWOA: >Problem: P, Epoch: 4, Current best: 0.8679166666666667, Global best: 0.8679166666666667, Runtime: 5.97417 seconds
2024/11/06 08:19:22 AM, INFO, mealpy.swarm_based.WOA.OriginalWOA: >Problem: P, Epoch: 5, Current best: 0.8762500000000001, Global best: 0.8762500000000001, Runtime: 5.59122 seconds
2024/11/06 08:19:27 AM, INFO, mealpy.swarm_based.WOA.OriginalWOA: >Problem: P, Epoch: 6, Curren

Solving problem: P using algorithm: OriginalWOA, on the: 2 trial, with best fitness: 0.8762500000000001


2024/11/06 08:19:59 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >Problem: P, Epoch: 1, Current best: 0.8375, Global best: 0.8375, Runtime: 6.89357 seconds
2024/11/06 08:20:06 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >Problem: P, Epoch: 2, Current best: 0.85, Global best: 0.85, Runtime: 6.32530 seconds
2024/11/06 08:20:12 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >Problem: P, Epoch: 3, Current best: 0.8583333333333334, Global best: 0.8583333333333334, Runtime: 6.22104 seconds
2024/11/06 08:20:18 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >Problem: P, Epoch: 4, Current best: 0.8583333333333334, Global best: 0.8583333333333334, Runtime: 6.08453 seconds
2024/11/06 08:20:23 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >Problem: P, Epoch: 5, Current best: 0.8666666666666667, Global best: 0.8666666666666667, Runtime: 5.61559 seconds
2024/11/06 08:20:29 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >Problem: P, Epoch: 6, Current best: 0.8708333333333333, Global best: 0.870833333

Solving problem: P using algorithm: OriginalGWO, on the: 1 trial, with best fitness: 0.8833333333333333


2024/11/06 08:21:03 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >Problem: P, Epoch: 1, Current best: 0.82625, Global best: 0.82625, Runtime: 7.05971 seconds
2024/11/06 08:21:10 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >Problem: P, Epoch: 2, Current best: 0.8416666666666667, Global best: 0.8416666666666667, Runtime: 6.42079 seconds
2024/11/06 08:21:16 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >Problem: P, Epoch: 3, Current best: 0.8512500000000001, Global best: 0.8512500000000001, Runtime: 5.88349 seconds
2024/11/06 08:21:21 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >Problem: P, Epoch: 4, Current best: 0.8554166666666667, Global best: 0.8554166666666667, Runtime: 5.65435 seconds
2024/11/06 08:21:26 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >Problem: P, Epoch: 5, Current best: 0.875, Global best: 0.875, Runtime: 5.07646 seconds
2024/11/06 08:21:31 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >Problem: P, Epoch: 6, Current best: 0.8791666666666667, Global best: 0.87916

Solving problem: P using algorithm: OriginalGWO, on the: 2 trial, with best fitness: 0.8833333333333333


2024/11/06 08:22:11 AM, INFO, mealpy.human_based.TLO.OriginalTLO: >Problem: P, Epoch: 1, Current best: 0.8470833333333334, Global best: 0.8470833333333334, Runtime: 13.49703 seconds
2024/11/06 08:22:23 AM, INFO, mealpy.human_based.TLO.OriginalTLO: >Problem: P, Epoch: 2, Current best: 0.8595833333333334, Global best: 0.8595833333333334, Runtime: 11.27780 seconds
2024/11/06 08:22:34 AM, INFO, mealpy.human_based.TLO.OriginalTLO: >Problem: P, Epoch: 3, Current best: 0.8595833333333334, Global best: 0.8595833333333334, Runtime: 11.58154 seconds
2024/11/06 08:31:18 AM, INFO, mealpy.human_based.TLO.OriginalTLO: >Problem: P, Epoch: 4, Current best: 0.8708333333333333, Global best: 0.8708333333333333, Runtime: 524.27967 seconds
2024/11/06 08:31:29 AM, INFO, mealpy.human_based.TLO.OriginalTLO: >Problem: P, Epoch: 5, Current best: 0.8708333333333333, Global best: 0.8708333333333333, Runtime: 11.05047 seconds
2024/11/06 08:31:41 AM, INFO, mealpy.human_based.TLO.OriginalTLO: >Problem: P, Epoch: 6, 

Solving problem: P using algorithm: OriginalTLO, on the: 1 trial, with best fitness: 0.875


2024/11/06 08:32:46 AM, INFO, mealpy.human_based.TLO.OriginalTLO: >Problem: P, Epoch: 1, Current best: 0.8470833333333334, Global best: 0.8470833333333334, Runtime: 13.75856 seconds
2024/11/06 08:32:59 AM, INFO, mealpy.human_based.TLO.OriginalTLO: >Problem: P, Epoch: 2, Current best: 0.8512500000000001, Global best: 0.8512500000000001, Runtime: 12.12907 seconds
2024/11/06 08:33:11 AM, INFO, mealpy.human_based.TLO.OriginalTLO: >Problem: P, Epoch: 3, Current best: 0.8625, Global best: 0.8625, Runtime: 11.90390 seconds
2024/11/06 08:33:22 AM, INFO, mealpy.human_based.TLO.OriginalTLO: >Problem: P, Epoch: 4, Current best: 0.8625, Global best: 0.8625, Runtime: 11.23706 seconds
2024/11/06 08:33:33 AM, INFO, mealpy.human_based.TLO.OriginalTLO: >Problem: P, Epoch: 5, Current best: 0.8625, Global best: 0.8625, Runtime: 11.15321 seconds
2024/11/06 08:33:44 AM, INFO, mealpy.human_based.TLO.OriginalTLO: >Problem: P, Epoch: 6, Current best: 0.86375, Global best: 0.86375, Runtime: 10.65314 seconds
20

Solving problem: P using algorithm: OriginalTLO, on the: 2 trial, with best fitness: 0.8720833333333333


2024/11/06 08:34:40 AM, INFO, mealpy.human_based.GSKA.OriginalGSKA: >Problem: P, Epoch: 1, Current best: 0.8470833333333334, Global best: 0.8470833333333334, Runtime: 5.69696 seconds
2024/11/06 08:34:45 AM, INFO, mealpy.human_based.GSKA.OriginalGSKA: >Problem: P, Epoch: 2, Current best: 0.8625, Global best: 0.8625, Runtime: 4.95762 seconds
2024/11/06 08:34:49 AM, INFO, mealpy.human_based.GSKA.OriginalGSKA: >Problem: P, Epoch: 3, Current best: 0.8679166666666667, Global best: 0.8679166666666667, Runtime: 4.32877 seconds
2024/11/06 08:34:53 AM, INFO, mealpy.human_based.GSKA.OriginalGSKA: >Problem: P, Epoch: 4, Current best: 0.8720833333333333, Global best: 0.8720833333333333, Runtime: 4.03263 seconds
2024/11/06 08:34:57 AM, INFO, mealpy.human_based.GSKA.OriginalGSKA: >Problem: P, Epoch: 5, Current best: 0.8720833333333333, Global best: 0.8720833333333333, Runtime: 3.84772 seconds
2024/11/06 08:35:01 AM, INFO, mealpy.human_based.GSKA.OriginalGSKA: >Problem: P, Epoch: 6, Current best: 0.87

Solving problem: P using algorithm: OriginalGSKA, on the: 1 trial, with best fitness: 0.8791666666666667


2024/11/06 08:35:30 AM, INFO, mealpy.human_based.GSKA.OriginalGSKA: >Problem: P, Epoch: 1, Current best: 0.8541666666666667, Global best: 0.8541666666666667, Runtime: 5.45078 seconds
2024/11/06 08:35:35 AM, INFO, mealpy.human_based.GSKA.OriginalGSKA: >Problem: P, Epoch: 2, Current best: 0.8625, Global best: 0.8625, Runtime: 4.57639 seconds
2024/11/06 08:35:39 AM, INFO, mealpy.human_based.GSKA.OriginalGSKA: >Problem: P, Epoch: 3, Current best: 0.8762500000000001, Global best: 0.8762500000000001, Runtime: 4.25897 seconds
2024/11/06 08:35:44 AM, INFO, mealpy.human_based.GSKA.OriginalGSKA: >Problem: P, Epoch: 4, Current best: 0.8762500000000001, Global best: 0.8762500000000001, Runtime: 4.35151 seconds
2024/11/06 08:35:48 AM, INFO, mealpy.human_based.GSKA.OriginalGSKA: >Problem: P, Epoch: 5, Current best: 0.8791666666666667, Global best: 0.8791666666666667, Runtime: 4.03467 seconds
2024/11/06 08:35:52 AM, INFO, mealpy.human_based.GSKA.OriginalGSKA: >Problem: P, Epoch: 6, Current best: 0.87

Solving problem: P using algorithm: OriginalGSKA, on the: 2 trial, with best fitness: 0.8791666666666667
Selected indices for trial1 with OriginalWOA: [ 1  5 13 14 19]
Feature names for trial1 with OriginalWOA: ['blood_pressure', 'red_blood_cells', 'potassium', 'hemoglobin', 'diabetes_mellitus']
Selected indices for trial1 with OriginalGWO: [ 5  9 14 18]
Feature names for trial1 with OriginalGWO: ['red_blood_cells', 'blood_glucose_random', 'hemoglobin', 'hypertension']
Selected indices for trial1 with OriginalTLO: [ 2  5  9 13 14 19]
Feature names for trial1 with OriginalTLO: ['specific_gravity', 'red_blood_cells', 'blood_glucose_random', 'potassium', 'hemoglobin', 'diabetes_mellitus']
Selected indices for trial1 with OriginalGSKA: [ 5  6 11 14 22]
Feature names for trial1 with OriginalGSKA: ['red_blood_cells', 'pus_cell', 'serum_creatinine', 'hemoglobin', 'pedal_edema']
Selected indices for trial2 with OriginalWOA: [ 5 11 14]
Feature names for trial2 with OriginalWOA: ['red_blood_cell